export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const INFO_USER_SUCCESS = 'INFO_USER_SUCCESS';
export const INFO_USER_FAIL = 'INFO_USER_FAIL';

export const ADD_APPOINTMENT_SUCCESS = 'ADD_APPOINTMENT_SUCCESS';
export const ADD_APPOINTMENT_FAIL = 'ADD_APPOINTMENT_FAIL';

export const MODIFY_APPOINTMENT_SUCCESS = 'MODIFY_APPOINTMENT_SUCCESS';
export const MODIFY_APPOINTMENT_FAIL = 'MODIFY_APPOINTMENT_FAIL';

export const LIST_APPOINTMENT_SUCCESS = 'LIST_APPOINTMENT_SUCCESS';
export const LIST_APPOINTMENT_FAIL = 'LIST_APPOINTMENT_FAIL';

export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS';
export const DELETE_APPOINTMENT_FAIL = 'DELETE_APPOINTMENT_FAIL';

export const LIST_USERS_SUCCESS = 'LIST_USER_SUCCESS';
export const LIST_USERS_FAIL = 'LIST_USER_FAIL';

export const ADD_AGENCY_SUCCESS = 'ADD_AGENCY_SUCCESS';
export const ADD_AGENCY_FAIL = 'ADD_AGENCY_FAIL';

export const MODIFY_AGENCY_SUCCESS = 'MODIFY_AGENCY_SUCCESS';
export const MODIFY_AGENCY_FAIL = 'MODIFY_AGENCY_FAIL';

export const LIST_AGENCY_SUCCESS = 'LIST_AGENCY_SUCCESS';
export const LIST_AGENCY_FAIL = 'LIST_AGENCY_FAIL';

export const DELETE_AGENCY_SUCCESS = 'DELETE_AGENCY_SUCCESS';
export const DELETE_AGENCY_FAIL = 'DELETE_AGENCY_FAIL';

export const ADD_PROPERTY_SUCCESS = 'ADD_PROPERTY_SUCCESS';
export const ADD_PROPERTY_FAIL = 'ADD_PROPERTY_FAIL';

export const MODIFY_PROPERTY_SUCCESS = 'MODIFY_PROPERTY_SUCCESS';
export const MODIFY_PROPERTY_FAIL = 'MODIFY_PROPERTY_FAIL';

export const LIST_PROPERTY_SUCCESS = 'LIST_PROPERTY_SUCCESS';
export const LIST_PROPERTY_FAIL = 'LIST_PROPERTY_FAIL';

export const DELETE_PROPERTY_SUCCESS = 'DELETE_PROPERTY_SUCCESS';
export const DELETE_PROPERTY_FAIL = 'DELETE_PROPERTY_FAIL';

export const ADD_PIECE_SUCCESS = 'ADD_PIECE_SUCCESS';
export const ADD_PIECE_FAIL = 'ADD_PIECE_FAIL';

export const MODIFY_PIECE_SUCCESS = 'MODIFY_PIECE_SUCCESS';
export const MODIFY_PIECE_FAIL = 'MODIFY_PROMODIFY_PIECE_FAILPERTY_FAIL';

export const DELETE_PIECE_SUCCESS = 'DELETE_PIECE_SUCCESS';
export const DELETE_PIECE_FAIL = 'DELETE_PIECE_FAIL';